[project]
authors = ["Ryan Oates <ryanoatsie@outlook.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "ryandavidoates"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
anthropic = ">=0.52.1,<0.53"
openai = ">=1.82.1,<2"
pip = ">=25.1.1,<26"
maven = ">=3.9.9,<4"
mistralai = ">=0.4.2,<0.5"
poetry = ">=2.1.3,<3"
python = ">=3.13.3,<3.14"
uvicorn = ">=0.34.3,<0.35"
python-socketio = ">=5.13.0,<6"
fastapi = ">=0.115.4,<0.116"
max = ">=25.4.0.dev2025060215,<26"
gradle = ">=8.11.1,<9"
